baseURL = "/"
disableLanguages = []
disqusShortname = ""
googleAnalytics = ""
languageCode = "it-it"
languageName = "It"
paginate = "6"
summaryLength = "10"
theme = "github.com/themefisher/twenty-twenty-hugo"
title = "Rimborso Adonit - Vsafe - Vbond"
[markup.goldmark.renderer]
unsafe = true
[[menu.desktop]]
URL = "contact"
name = "Contatti"
weight = 1
[[menu.main]]
URL = "/"
name = "Home"
weight = 1
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "contact"
name = "Contatti"
weight = 4
[[menu.main]]
URL = "sample-page"
name = "Sample Page"
weight = 5
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Detrattori e strilloni del web"
description = "Pensi di aver perso per sempre i tuoi soldi dopo averli investiti nei progetti “Vertical Gain”, “Adonit”, “Vsafe” o “Vbond”? Questo sito potrebbe aiutarti."
[params.banner]
heading = "Pensi di aver perso per sempre i tuoi soldi dopo averli investiti nei progetti \"Vertical Gain\", \"Adonit\", \"Vsafe\" o \"Vbond\"? Questo sito potrebbe aiutarti."
image = "images/6iclkj.jpg"
[params.blog]
heading = "Ci siamo fidati, abbiamo atteso, siamo stati pazienti, ma non è bastato. Abbiamo pertanto deciso, supportati dall'associazione \"Il gatto e la volpe nel web\" (che ringraziamo), di intraprendere un'azione collettiva per cercare di riavere i nostri soldi."
[params.call_to_action]
[params.footer]
content = "Questo sito non rappresenta una testata giornalistica in quanto viene aggiornato senza  alcuna periodicità. Non può pertanto considerarsi un prodotto editoriale ai sensi della  legge n° 62 del 7.03.2001. Gli autori del sito non sono responsabili dei siti collegati tramite link né del loro contenuto che può essere soggetto a variazioni nel tempo."
copyright = "Creato a Giugno 2022 da \"detrattori\", \"strilloni del web\", ma soprattutto persone oneste."
enable = true
title = "Avviso per i visitatori"
[params.social]
[taxonomies]
